# action.yml
name: 'Run Circle-CI on Label - Circle API v2'
description: 'Runs a Circle-CI Build upon adding a new label to PR'
inputs:
  circle_ci_token:  # secret token for circle CI Rest API
    description: 'Token for Circle-CI'
    required: true
    default: ''
  circle_ci_project_url:
    description: 'URL for circle-ci project'
    required: true
    default: ''
  circle_ci_job_params:
    description: 'List of params to pass along to circle api. ex: "Param1":"Value1", "Param2":"Value2"'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.circle_ci_token }}
    - ${{ inputs.circle_ci_project_url }}
    - ${{ inputs.circle_ci_job_params }}
